import java.util.List;

public interface Piece {

    Position position = new Position();

    /**
     * This method checks if a move is valid, given a Move.
     * This method MUST be overwritten by each piece with that piece's given movement rules.
     * @param move The Move to check
     * @return True or false dependent on if the move is valid.
     */
    public static boolean isMoveValid(Move move) {
        return true;
    }

    /**
     * Returns an (Array)List of the potential moves for the piece.
     * These should then be displayed to the user in the GUI, and then they can select which move they'd like to make.
     * After that, the selected Move generated by this function can be passed to Board.movePiece().
     * @return The (Array)List of valid moves.
     */
    public List<Move> getPotentialMoves();

}
